- name: Generate pre-register-users script
  template:
    src: templates/pre-register-user.sh.j2
    dest: ./pre-register-users.sh
    mode: 0755

- name: Delete user script pod
  ignore_errors: yes
  shell: |
    kubectl delete pod pre-register-user-script -n vault

- name: Delete Script Configmap 
  ignore_errors: yes
  shell: |
    kubectl delete configmap pre-register-users-script -n vault

- name: Create configmap for network configuration file
  shell: |
    kubectl -n vault create configmap pre-register-users-script --from-file=pre-register-users.sh=./pre-register-users.sh

- name: Create secret for credentials
  template:
    src: pre_register_setup/trv_secret_credentials.yaml.j2
    dest: "pre_register_setup/trv_secret_credentials.yaml"
    mode: 0755

- name: Launch secret for credentials
  shell: |
    kubectl apply -f pre_register_setup/trv_secret_credentials.yaml  

- name: Create Pod for pre-register-users
  template:
    src: pre_register_setup/trv_pre_register_pod.yaml.j2
    dest: "pre_register_setup/trv_pre_register_pod.yaml"
    mode: 0755

- name: Launch Pod for pre-register-users
  shell: |
    kubectl apply -f pre_register_setup/trv_pre_register_pod.yaml 

- name: Pod logs
  shell: |
    sleep 30
    kubectl -n vault logs -f pre-register-user-script
  register: pod_logs

- name: Pod logs 
  debug:
    msg: '{{ pod_logs.stdout_lines }}'

- name: upload ca user token to aws secrets manager
  shell: |
    aws secretsmanager create-secret --name {{ network.org_name }}-{{ env }}-ca-app-user-token --description "Ca App User token" --secret-string {{ ca_user_token }}
  when: ca_user_token_status == "null" 

- name: Delete user script pod
  shell: |
    kubectl delete pod pre-register-user-script -n vault

- name: Delete Script Configmap 
  shell: |
    kubectl delete configmap pre-register-users-script -n vault

- name: Delete User Creds Secret
  shell: |
    kubectl delete -f pre_register_setup/trv_secret_credentials.yaml

- name: Delete pre-register-users-script
  file:
    state: absent
    path: ./pre-register-users.sh