access_id: ""
access_key: ""
region: ""
cluster_name: ""
account: ""
gitops_repo_url: "github.com/openidl-org/openidl-aais-gitops.git"
gitops_repo_branch: "baf-automation"
gitops_repo_user: ""
gitops_repo_user_token: ""
gitops_repo_user_email: ""
ordererorg_domain: "analytics.techiething.com"
domain: "analytics.techiething.com"
internal_domain: "analytics.internal.techiething.com"
env: "dev"
add_org: false 
registry: ""

network:
  org_name: "analytics"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: ""
      domain: ""
      org_status: ""
  channels:
  - name: analytics-aais
    chaincode:
      name: openidl-cc-aais-carriers
      version: 1
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: cognito-fabric-node14-helm
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        name: "analytics_aais_pdc"
        policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: cognito-fabric-node14-helm
      repo_path: openidl-chaincode/chaincode/openidl
