access_id: ""
access_key: ""
region: ""
cluster_name: ""
account: ""
gitops_repo_url: "github.com/daredevils2o21/openidl-aais-gitops.git"
gitops_repo_branch: "develop"
gitops_repo_user: ""
gitops_repo_user_token: ""
gitops_repo_user_email: ""
ordererorg_domain: "openidl.aais.com"
domain: "trv.travelersdemo.com
internal_domain: "trv.internal.travelersdemo.com"
env: "dev"
add_org: "" 
registry: "246701835898.dkr.ecr.us-east-1.amazonaws.com"
chaincode_version: ""
node_type: "carrier"

network:
  org_name: "trv"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: "trv"
      domain: "trv.travelersdemo.com"
      org_status: ""
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: "develop"
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        name: "anal_trv_pdc"
        policy: "OR('analyticsMSP.member', 'trvMSP.member')"
  - name: anal-trv
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: "develop"
      repo_path: openidl-chaincode/chaincode/openidl
