- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(true) }}"
  tasks:
    - name: Get vault root token
      shell: |
        aws secretsmanager get-secret-value --secret-id {{ network.org_name }}-{{ env }}-vault-unseal-key-1 --version-stage AWSCURRENT | jq -r .SecretString
      register: vault

    - include_role:
        name: "baf/network"
      vars:
        vault_token: "{{ vault.stdout }}"
