- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    - name: Get KMS ID
      shell: |
        aws kms describe-key --key-id alias/vault-test-kms-key | jq -r .KeyMetadata.KeyId
      register: output

    - include_role:
        name: "vault"
      vars:
        vault_kms_key_id: "{{ output.stdout }}"
